### ISSUE TITLE
Bridge's indicators (active and code) return undefined img on mobile

### ISSUE THREAD

**Issue by corvardt** [bradthomasbrown/dizzyhavoc-web#57]
The rest is fine but indicators aren't displayed

Safari/Brave
![image](https://github.com/bradbrown-llc/dizzyhavoc-web/assets/124924375/766297f9-acf5-4d5e-a429-dbede8f58fbf)

**Comment by bradthomasbrown** [comment]
closing this as we're archiving this and moving to the `dizzyhavoc` repo.
recreating this, refer to [`dizzyhavoc#15`](https://github.com/bradthomasbrown/dizzyhavoc/issues/15)
